version: '3'
services:
  frontend:
    build:
      context: ./frontend/web/riskmanager
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/riskmanager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
